services:
  
  postgres:
    ports:
      - "5432:5432"
  
  opensearch:
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-misp1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:80"
      - "5677:5677"
      - "5678:5678"
    entrypoint: [ "bash", "-c", "./entrypoint.dev.sh" ]
    environment:
      WATCHFILES_FORCE_POLLING: true
      WATCHFILES_POLLING_INTERVAL: 1
    volumes:
      - ./api:/code
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    ports:
      - "5679:5679"
    command:
      [
        "sh",
        "-c",
        "poetry run python -m debugpy --listen 0.0.0.0:5679 -m celery -A app.worker.tasks worker --loglevel=debug --hostname=worker1@%h --concurrency=1 --pool=solo",
      ]
    volumes:
      - ./api:/code
    extra_hosts:
      - "host.docker.internal:host-gateway"


  beat:
    ports:
      - "5680:5680"
    command:
      [
        "sh",
        "-c",
        "poetry run python -m debugpy --listen 0.0.0.0:5680 -m celery -A app.worker.tasks beat --loglevel=debug --scheduler redbeat.RedBeatScheduler"
      ]
    volumes:
      - ./api:/code
    extra_hosts:
      - "host.docker.internal:host-gateway"

  flower:
    ports:
      - "5555:5555"
    command: poetry run celery -A app.worker.tasks flower --loglevel=debug --persistent=True --auto_refresh=True --state_save_interval=1000 -n worker1@%h

  frontend:
    command: [ nginx-debug, '-g', 'daemon off;' ]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  dashboards:
    environment:
      OPENSEARCH_HOSTS: "http://${OPENSEARCH_HOSTNAME:-opensearch}:${OPENSEARCH_PORT:-9200}"
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --user admin:$$OPENSEARCH_DASHBOARDS_PASSWORD -k -X GET http://localhost:5601/api/status | grep '\"state\":\"green\"'"
        ]

  redis-commander:
    image: rediscommander/redis-commander
    depends_on:
      - redis
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    ports:
      - "8081:8081"

  modules:
    ports:
      - "6666:6666"